src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from main.views import IndexView

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("admin/", admin.site.urls),
    path("students/", include("students.urls")),
    path("teachers/", include("teachers.urls")),
    path("groups/", include("groups.urls")),
    path("main/", include("main.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("oauth/", include("social_django.urls", namespace="social")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/main/urls.py
from django.urls import path

from main.views import (
    IndexView,
    UserLogin,
    UserLogout,
    UserRegistration,
    SendEmailView,
    ActivateUserView,
    ProfileData,
)

app_name = "main"

urlpatterns = [
    path("index/", IndexView.as_view(), name="index"),
    path("login/", UserLogin.as_view(), name="login"),
    path("logout/", UserLogout.as_view(), name="logout"),
    path("registration/", UserRegistration.as_view(), name="registration"),
    path("send-email/", SendEmailView.as_view(), name="send_email"),
    path(
        "activate/<str:uuid64>/<str:token>/",
        ActivateUserView.as_view(),
        name="active_user",
    ),
    path("profile/", ProfileData.as_view(), name="profile"),
]

src/main/models.py
from django.contrib.auth import get_user_model
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.core.validators import MinLengthValidator, RegexValidator
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from phonenumber_field.modelfields import PhoneNumberField

from main.managers import CustomerManager
from students.utils.validators import first_name_validator


class Customer(AbstractBaseUser, PermissionsMixin):
    first_name = models.CharField(_("Name"), max_length=150, blank=True)
    last_name = models.CharField(_("Surname"), max_length=150, blank=True)
    phone_number = PhoneNumberField(
        _("phone_number"),
        null=True,
        blank=True,
        validators=[
            RegexValidator(
                regex=r"^\+?1?\d{9,15}$",
                message="Phone number must be entered in the format: '+666666666'. Up to 15 digits allowed.",
            )
        ],
    )
    email = models.EmailField(_("email address"), null=True, blank=True)
    is_staff = models.BooleanField(
        _("staff status"),
        default=False,
        help_text=_("Designates whether the user can log into this admin site."),
    )
    is_active = models.BooleanField(
        _("active"),
        default=True,
        help_text=_(
            "Designates whether this user should be treated as active. " "Unselect this instead of deleting accounts."
        ),
    )
    date_joined = models.DateTimeField(_("date joined"), default=timezone.now)
    department = models.CharField(_("department"), max_length=300, null=True, blank=True)
    birth_date = models.DateTimeField(_("birth_date"), null=True, blank=True)
    avatar = models.ImageField(_("avatar"), upload_to="images/profiles", null=True, blank=True)

    objects = CustomerManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _("customer")
        verbose_name_plural = _("customers")

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = "%s %s" % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def get_period_of_registration(self):
        return f"Time on site: {timezone.now() - self.date_joined}"

    def __str__(self):
        return f"{self.phone_number}"


class UserProfile(models.Model):
    TYPE_CHOICES = [
        ("Teacher", "Teacher"),
        ("Student", "Student"),
        ("Mentor", "Mentor"),
    ]
    GENDER_CHOICES = [
        ("M", "Male"),
        ("F", "Female"),
        ("O", "Another"),
    ]
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE)
    # photo = models.ImageField(upload_to="images/profiles", blank=True, null=True)
    # phone_number = PhoneNumberField(blank=True)
    user_type = models.CharField(max_length=50, choices=TYPE_CHOICES, blank=True, null=True)
    gender = models.CharField(max_length=20, choices=GENDER_CHOICES, blank=True, null=True)
    instagram_url = models.URLField(max_length=200, blank=True, null=True)
    city_name = models.CharField(max_length=100, blank=True, default="Dnipro")
    latitude = models.FloatField(blank=True, default=48)
    longitude = models.FloatField(blank=True, default=35)

    def __str__(self):
        return f"{self.user.first_name}_{self.user.last_name} {self.user.phone_number}"


class Person(models.Model):
    first_name = models.CharField(
        max_length=150,
        blank=True,
        null=True,
        validators=[MinLengthValidator(3), first_name_validator],
    )
    last_name = models.CharField(max_length=150, blank=True, null=True)
    email = models.EmailField(max_length=150)

    class Meta:
        abstract = True

src/templates/users_data/profile.html
{% extends "index.html" %}
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA17wG-jEaVAXjFLSuBJ5JgLL72Yf2yfzI"></script>
{% block content %}
    <div style="display: flex; align-items: center; justify-content: space-between;">
        <div style="flex-shrink: 0; margin-left: 500px;">
            <ul>
                <p>
                    {% if data.user.avatar %}
                        <img src="{{ data.user.avatar.url }}" alt="{{ data.user.first_name }} photo" width="200">
                    {% else %}
                        No photo
                    {% endif %}
                </p>
            </ul>
        </div>
        <div style="flex-grow: 1; margin-right: 200px;">
            <ul>
                <p><strong>{{ data.user.first_name }} {{ data.user.last_name }}</strong></p>
                <p><strong>Gender:</strong> {{ data.get_gender_display }}</p>
                <p><strong>Phone Number:</strong> {{ data.user.phone_number }}</p>
                <p><strong>User Type:</strong> {{ data.get_user_type_display }}</p>
                <p><strong>City:</strong> {{ data.city_name }}</p>
                <p><strong>Latitude:</strong> {{ data.latitude }}</p>
                <p><strong>Longitude:</strong> {{ data.longitude }}</p>
                <p><strong>Instagram URL: </strong><a href="{{ data.instagram_url }}">{{ data.instagram_url }}</a></p>
            </ul>
        </div>
    </div>
    <div style="margin-top: 20px; text-align: center;">
        <div style="width: 60%; margin: 0 auto; background-color: #fffff0; height: 3px;"></div>
        <div id="map" style="height: 400px; width: 600px; margin: 20px auto;"></div>
    </div>
    <script>
        function initMap() {
            var map = new google.maps.Map(document.getElementById('map'), {
                center: {lat: {{ data.latitude }}, lng: {{ data.longitude }}},
                zoom: 2
            });
            new google.maps.Marker({
                position: {lat: {{ data.latitude }}, lng: {{ data.longitude }}},
                map: map,
                title: '{{ data.name }}'
            });
        }
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA17wG-jEaVAXjFLSuBJ5JgLL72Yf2yfzI&callback=initMap"
            async defer></script>
{% endblock content %}