src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from main.views import IndexView

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("admin/", admin.site.urls),
    path("students/", include("students.urls")),
    path("teachers/", include("teachers.urls")),
    path("groups/", include("groups.urls")),
    path("main/", include("main.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("oauth/", include("social_django.urls", namespace="social")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/main/urls.py
from django.urls import path

from main.views import (
    IndexView,
    UserLogin,
    UserLogout,
    UserRegistration,
    SendEmailView,
    ActivateUserView,
    ProfileData,
)

app_name = "main"

urlpatterns = [
    path("index/", IndexView.as_view(), name="index"),
    path("login/", UserLogin.as_view(), name="login"),
    path("logout/", UserLogout.as_view(), name="logout"),
    path("registration/", UserRegistration.as_view(), name="registration"),
    path("send-email/", SendEmailView.as_view(), name="send_email"),
    path(
        "activate/<str:uuid64>/<str:token>/",
        ActivateUserView.as_view(),
        name="active_user",
    ),
    path("profile/", ProfileData.as_view(), name="profile"),
]

src/students/urls.py
from django.urls import path

from students.views import (
    CreateStudentView,
    UpdateStudentView,
    DeleteStudentView,
    StudentListView,
)

app_name = "students"

urlpatterns = [
    path("", StudentListView.as_view(), name="get_students"),
    path("create/", CreateStudentView.as_view(), name="create_student"),
    path("update/<uuid:uuid>/", UpdateStudentView.as_view(), name="update_student"),
    path("delete/<uuid:uuid>/", DeleteStudentView.as_view(), name="delete_student"),
]

src/students/models.py
import datetime
import random
from uuid import uuid4

from django.db import models
from django.utils.translation import gettext_lazy as _
from faker import Faker

from groups.models import Group
from main.models import Person


class Student(Person):
    uuid = models.UUIDField(default=uuid4, primary_key=True, editable=False, unique=True, db_index=True)
    avatar = models.ImageField(upload_to="images/students", blank=True, null=True)
    grade = models.PositiveSmallIntegerField(default=0, null=True)
    birth_date = models.DateField(null=True)
    group = models.ForeignKey(to=Group, null=True, on_delete=models.CASCADE)
    resume = models.FileField(upload_to="resumes/", blank=True, null=True)

    class Meta:
        verbose_name = _("Student")
        verbose_name_plural = _("All students")

    def age(self):
        try:
            return datetime.datetime.now().year - self.birth_date.year
        except AttributeError:
            return None

    def __str__(self):
        return f"{self.first_name}_{self.last_name} {self.email}"

    @classmethod
    def generate_instances(cls, count):
        faker = Faker()
        for i in range(count):
            cls.objects.create(
                first_name=faker.first_name(),
                last_name=faker.last_name(),
                email=faker.email(),
                grade=random.randint(1, 100),
                birth_date=faker.date_time_between(start_date="-40y", end_date="-18y"),
                group_id=1,
            )

src/students/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm

from students.models import Student


class StudentForm(ModelForm):
    class Meta:
        model = Student
        fields = (
            "avatar",
            "first_name",
            "last_name",
            "email",
            "grade",
            "group",
            "resume",
        )

    @staticmethod
    def normalize_text(text: str) -> str:
        return text.strip().capitalize()

    def clean_email(self):
        email = self.cleaned_data["email"]

        if "@yandex" in email.lower():
            raise ValidationError("Yandex email is forbidden to use in our country!!!")

        return email

    def clean_last_name(self):
        return self.normalize_text(self.cleaned_data["last_name"])

    def clean_first_name(self):
        return self.normalize_text(self.cleaned_data["first_name"])

    def clean(self):
        cleaned_data = super().clean()

        first_name = cleaned_data["first_name"]
        last_name = cleaned_data["last_name"]

        if first_name == last_name:
            raise ValidationError("First name and last name cant be equal!!!")

        return cleaned_data

src/students/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    UpdateView,
    DeleteView,
    ListView,
)

from students.forms import StudentForm
from students.models import Student


class StudentListView(LoginRequiredMixin, ListView):
    model = Student
    template_name = "students/list.html"
    context_object_name = "students"

    def get_queryset(self):
        queryset = super().get_queryset()
        search_text = self.request.GET.get("search_text", "")

        if search_text:
            search_fields = [
                "last_name__icontains",
                "first_name__icontains",
                "email__icontains",
            ]
            or_filter = Q()

            for field in search_fields:
                or_filter |= Q(**{field: search_text})

            queryset = queryset.filter(or_filter)

        return queryset


class CreateStudentView(LoginRequiredMixin, CreateView):
    template_name = "students/create.html"
    form_class = StudentForm
    initial = {"grade": "50"}
    success_url = reverse_lazy("students:get_students")


class UpdateStudentView(UpdateView):
    template_name = "students/update.html"
    form_class = StudentForm
    pk_url_kwarg = "uuid"
    queryset = Student.objects.all()
    success_url = reverse_lazy("students:get_students")


class DeleteStudentView(DeleteView):
    template_name = "students/delete.html"
    form_class = StudentForm
    pk_url_kwarg = "uuid"
    queryset = Student.objects.all()
    success_url = reverse_lazy("students:get_students")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = StudentForm(instance=self.object)
        return context

src/templates/students/create.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <form method="POST" style="width: 25em; margin: auto" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success" value="Create">Create student</button>
    </form>
{% endblock content %}

src/templates/students/delete.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <form method="POST" style="width: 25em; margin: auto">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success" value="Delete">Delete student</button>
    </form>
{% endblock content %}

src/templates/students/list.html
{% extends "index.html" %}
{% block content %}
    <div class="search-form mt-3">
        <form class="d-flex" method="get" action="{% url 'students:get_students' %}">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="search_text">
            <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
    </div>


    <table class="table table-dark table-striped">
        <thead>
        <tr>
            <th scope="col">Avatar</th>
            <th scope="col">First name</th>
            <th scope="col">Last name</th>
            <th scope="col">Email</th>
            <th scope="col">Grade</th>
            <th scope="col">Birth date</th>
            <th scope="col">Age</th>
            <th scope="col">Resume</th>
            <th scope="col">Edit</th>
            <th scope="col">Delete</th>
        </tr>
        </thead>
        <tbody>
        {% for student in students %}
            <tr>
                <td>
                    {% if student.avatar %}
                        <img src="{{ student.avatar.url }}" alt="{{ student.first_name }} Avatar" width="50">
                    {% else %}
                        No Avatar
                    {% endif %}
                </td>
                <td>{{ student.first_name }}</td>
                <td>{{ student.last_name }}</td>
                <td>{{ student.email }}</td>
                <td>{{ student.grade }}</td>
                <td>{{ student.birth_date|default:"Unknown" }}</td>
                {% if student.birth_date %}
                    <td>{{ student.age }}</td>
                {% else %}
                    <td>Unknown age</td>
                {% endif %}
                <td>
                    {% if student.resume %}
                        <a type="button" class="btn btn-primary"
                           href="{{ student.resume.url }}" target="_blank">View Resume</a>
                    {% else %}
                        No Resume
                    {% endif %}
                </td>
                <th>
                    <a type="button" class="btn btn-warning"
                       href="{% url 'students:update_student' student.pk %}"
                    >Edit</a>
                </th>
                <th>
                    <a type="button" class="btn btn-danger"
                       href="{% url 'students:delete_student' student.pk %}"
                    >Delete</a>
                </th>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock content %}

src/templates/students/update.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <form method="POST" style="width: 25em; margin: auto" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success" value="Update">Update student</button>
    </form>
{% endblock content %}