src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from main.views import IndexView

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("admin/", admin.site.urls),
    path("students/", include("students.urls")),
    path("teachers/", include("teachers.urls")),
    path("groups/", include("groups.urls")),
    path("main/", include("main.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("oauth/", include("social_django.urls", namespace="social")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/groups/urls.py
from django.urls import path

from groups.views import (
    GroupListView,
    CreateGroupView,
    UpdateGroupView,
    DeleteGroupView,
)

app_name = "groups"

urlpatterns = [
    path("", GroupListView.as_view(), name="get_groups"),
    path("create", CreateGroupView.as_view(), name="create_groups"),
    path("update/<int:pk>/", UpdateGroupView.as_view(), name="update_group"),
    path("delete/<int:pk>/", DeleteGroupView.as_view(), name="delete_group"),
]

src/main/urls.py
from django.urls import path

from main.views import (
    IndexView,
    UserLogin,
    UserLogout,
    UserRegistration,
    SendEmailView,
    ActivateUserView,
    ProfileData,
)

app_name = "main"

urlpatterns = [
    path("index/", IndexView.as_view(), name="index"),
    path("login/", UserLogin.as_view(), name="login"),
    path("logout/", UserLogout.as_view(), name="logout"),
    path("registration/", UserRegistration.as_view(), name="registration"),
    path("send-email/", SendEmailView.as_view(), name="send_email"),
    path(
        "activate/<str:uuid64>/<str:token>/",
        ActivateUserView.as_view(),
        name="active_user",
    ),
    path("profile/", ProfileData.as_view(), name="profile"),
]

src/teachers/urls.py
from django.urls import path

from teachers.views import (
    TeacherListView,
    CreateTeacherView,
    UpdateTeachersView,
    DeleteTeacherView,
    GroupDetailsView,
)

app_name = "teachers"

urlpatterns = [
    path("", TeacherListView.as_view(), name="get_teachers"),
    path("create", CreateTeacherView.as_view(), name="create_teacher"),
    path("update/<int:pk>/", UpdateTeachersView.as_view(), name="update_teacher"),
    path("delete/<int:pk>/", DeleteTeacherView.as_view(), name="delete_teacher"),
    path("group-details/<int:pk>/", GroupDetailsView.as_view(), name="group_details"),
]

src/groups/models.py
from random import randint

from django.db import models
from django.utils.translation import gettext_lazy as _
from faker import Faker

from groups.utils.validators import start_date_validator, student_count_validator
from main.utils.validators import subject_validator


class Group(models.Model):
    name = models.CharField(max_length=200, null=True)
    number = models.PositiveSmallIntegerField()
    students_count = models.PositiveSmallIntegerField(validators=[student_count_validator])
    start_date = models.DateField(null=True, validators=[start_date_validator])
    subject = models.CharField(max_length=100, blank=True, null=True, validators=[subject_validator])
    description = models.TextField(null=True)

    class Meta:
        verbose_name = _("Group")
        verbose_name_plural = _("All groups")

    def __str__(self):
        return f"{self.name} ({self.id})"

    @classmethod
    def generate_instances(cls, count):
        faker = Faker()
        for i in range(count):
            cls.objects.create(
                name=faker.company(),
                number=randint(1, 300),
                students_count=randint(10, 30),
                start_date=faker.date_this_century(),
                subject=faker.word(
                    ext_word_list=[
                        "Math",
                        "Chemistry",
                        "Music",
                        "Physics",
                        "History",
                        "IT",
                    ]
                ),
                description=faker.sentence(nb_words=10),
            )

src/teachers/models.py
from random import randint

from django.core.validators import MinValueValidator
from django.db import models
from django.utils.translation import gettext_lazy as _
from faker import Faker

from groups.models import Group
from main.models import Person
from main.utils.validators import subject_validator


class Teacher(Person):
    avatar = models.ImageField(upload_to="images/teachers", blank=True, null=True)
    age = models.PositiveSmallIntegerField(null=True, validators=[MinValueValidator(15)])
    work_experience = models.PositiveSmallIntegerField(null=True)
    english_level = models.BooleanField(null=True)
    subject = models.CharField(max_length=100, blank=True, null=True, validators=[subject_validator])
    group = models.ManyToManyField(
        to=Group,
    )

    class Meta:
        verbose_name = _("Teacher")
        verbose_name_plural = _("All teachers")

    def __str__(self):
        return f"{self.first_name}_{self.last_name} {self.email}"

    @classmethod
    def generate_instances(cls, count):
        faker = Faker()
        for i in range(count):
            cls.objects.create(
                first_name=faker.first_name(),
                last_name=faker.last_name(),
                email=faker.email(),
                age=randint(20, 100),
                work_experience=randint(1, 20),
                english_level=faker.boolean(chance_of_getting_true=50),
                subject=faker.word(
                    ext_word_list=[
                        "Math",
                        "Chemistry",
                        "Music",
                        "Physics",
                        "History",
                        "IT",
                    ]
                ),
            )

src/groups/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm

from groups.models import Group


class GroupForm(ModelForm):
    class Meta:
        model = Group
        fields = (
            "name",
            "number",
            "students_count",
            "start_date",
            "subject",
            "description",
        )

    def clean_students_count(self):
        students_count = self.cleaned_data["students_count"]
        if students_count > 30:
            raise ValidationError("The number of students in a group cannot be more than 30")
        return students_count

src/teachers/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm

from teachers.models import Teacher


class TeacherForm(ModelForm):
    class Meta:
        model = Teacher
        fields = (
            "avatar",
            "first_name",
            "last_name",
            "email",
            "age",
            "work_experience",
            "english_level",
            "subject",
            "group",
        )

    @staticmethod
    def normal_text(text: str):
        return text.strip().capitalize()

    def clean_first_name(self):
        return self.normal_text(self.cleaned_data["first_name"])

    def clean_last_name(self):
        return self.normal_text(self.cleaned_data["last_name"])

    def clean(self):
        cleaned_data = super().clean()

        age = cleaned_data["age"]
        work_experience = cleaned_data["work_experience"]

        if work_experience >= age - 10:
            raise ValidationError("Work_experience must be at least 10 units less than your age")

        return cleaned_data

src/groups/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from groups.forms import GroupForm
from groups.models import Group


class GroupListView(LoginRequiredMixin, ListView):
    model = Group
    template_name = "groups/list.html"
    context_object_name = "groups"

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset


class CreateGroupView(LoginRequiredMixin, CreateView):
    template_name = "groups/create.html"
    form_class = GroupForm
    initial = {"start_date": "2007-10-25"}
    success_url = reverse_lazy("groups:get_groups")


class UpdateGroupView(UpdateView):
    template_name = "groups/update.html"
    form_class = GroupForm
    pk_url_kwarg = "pk"
    queryset = Group.objects.all()
    success_url = reverse_lazy("groups:get_groups")


class DeleteGroupView(DeleteView):
    template_name = "groups/delete.html"
    form_class = GroupForm
    pk_url_kwarg = "pk"
    queryset = Group.objects.all()
    success_url = reverse_lazy("groups:get_groups")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = GroupForm(instance=self.object)
        return context

src/teachers/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    CreateView,
    UpdateView,
    DeleteView,
    DetailView,
)

from groups.models import Group
from teachers.forms import TeacherForm
from teachers.models import Teacher


class TeacherListView(LoginRequiredMixin, ListView):
    model = Teacher
    template_name = "teachers/list.html"
    context_object_name = "teachers"

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset


class CreateTeacherView(LoginRequiredMixin, CreateView):
    template_name = "teachers/create.html"
    form_class = TeacherForm
    success_url = reverse_lazy("teachers:get_teachers")


class UpdateTeachersView(UpdateView):
    template_name = "teachers/update.html"
    form_class = TeacherForm
    pk_url_kwarg = "pk"
    queryset = Teacher.objects.all()
    success_url = reverse_lazy("teachers:get_teachers")


class DeleteTeacherView(DeleteView):
    template_name = "teachers/delete.html"
    form_class = TeacherForm
    pk_url_kwarg = "pk"
    queryset = Teacher.objects.all()
    success_url = reverse_lazy("teachers:get_teachers")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = TeacherForm(instance=self.object)
        return context


class GroupDetailsView(DetailView):
    model = Group
    template_name = "teachers/groups.html"
    context_object_name = "group"

    def get_object(self, **kwargs):
        return get_object_or_404(Group.objects.all(), pk=self.kwargs["pk"])

src/templates/teachers/create.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <form method="POST" style="width: 25em; margin: auto" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success" value="Create">Create teacher</button>
    </form>
{% endblock content %}

src/templates/teachers/delete.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <form method="POST" style="width: 25em; margin: auto">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success" value="Delete">Delete student</button>
    </form>
{% endblock content %}

src/templates/teachers/groups.html
{% extends "index.html" %}

{% block content %}
    {% csrf_token %}
    <div>
        <p>Name: {{ group.name }}</p>
        <p>Number: {{ group.number }}</p>
        <p>Students_count: {{ group.students_count }}</p>
        <p>Start_date: {{ group.start_date }}</p>
        <p>Subject: {{ group.subject }}</p>
        <p>Description: {{ group.description }}</p>
    </div>
{% endblock content %}

src/templates/teachers/list.html
{% extends "index.html" %}

{% block content %}
    <table class="table table-dark table-striped">
        <thead>
        <tr>
            <th scope="col">Avatar</th>
            <th scope="col">First name</th>
            <th scope="col">Last name</th>
            <th scope="col">Email</th>
            <th scope="col">Age</th>
            <th scope="col">Work experience</th>
            <th scope="col">English level</th>
            <th scope="col">Subject</th>
            <th scope="col">Groups</th>
            <th scope="col">Edit</th>
            <th scope="col">Delete</th>
        </tr>
        </thead>
        <tbody>
        {% for teacher in teachers %}
            <tr>
                <td>
                    {% if teacher.avatar %}
                        <img src="{{ teacher.avatar.url }}" alt="{{ teacher.first_name }} Avatar" width="50">
                    {% else %}
                        No Avatar
                    {% endif %}
                </td>
                <td>{{ teacher.first_name }}</td>
                <td>{{ teacher.last_name }}</td>
                <td>{{ teacher.email }}</td>
                <td>{{ teacher.age|default:"Unknown age" }}</td>
                <td>{{ teacher.work_experience }}</td>
                <td>{{ teacher.english_level|default:"Unknown" }}</td>
                <td>{{ teacher.subject }}</td>
                <th>
                    {% for group in teacher.group.all %}
                        <p><a type="button" class="btn btn-info"
                              href="{% url 'teachers:group_details' group.pk %}"
                        >{{ group.name }}</a></p>
                    {% endfor %}
                </th>
                <th>
                    <a type="button" class="btn btn-warning"
                       href="{% url 'teachers:update_teacher' teacher.pk %}"
                    >Edit</a>
                </th>
                <th>
                    <a type="button" class="btn btn-danger"
                       href="{% url 'teachers:delete_teacher' teacher.pk %}"
                    >Delete</a>
                </th>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock content %}

src/templates/teachers/update.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <form method="POST" style="width: 25em; margin: auto" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success" value="Update">Update teacher</button>
    </form>
{% endblock content %}