src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from main.views import IndexView

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("admin/", admin.site.urls),
    path("students/", include("students.urls")),
    path("teachers/", include("teachers.urls")),
    path("groups/", include("groups.urls")),
    path("main/", include("main.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("oauth/", include("social_django.urls", namespace="social")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/groups/urls.py
from django.urls import path

from groups.views import (
    GroupListView,
    CreateGroupView,
    UpdateGroupView,
    DeleteGroupView,
)

app_name = "groups"

urlpatterns = [
    path("", GroupListView.as_view(), name="get_groups"),
    path("create", CreateGroupView.as_view(), name="create_groups"),
    path("update/<int:pk>/", UpdateGroupView.as_view(), name="update_group"),
    path("delete/<int:pk>/", DeleteGroupView.as_view(), name="delete_group"),
]

src/main/urls.py
from django.urls import path

from main.views import (
    IndexView,
    UserLogin,
    UserLogout,
    UserRegistration,
    SendEmailView,
    ActivateUserView,
    ProfileData,
)

app_name = "main"

urlpatterns = [
    path("index/", IndexView.as_view(), name="index"),
    path("login/", UserLogin.as_view(), name="login"),
    path("logout/", UserLogout.as_view(), name="logout"),
    path("registration/", UserRegistration.as_view(), name="registration"),
    path("send-email/", SendEmailView.as_view(), name="send_email"),
    path(
        "activate/<str:uuid64>/<str:token>/",
        ActivateUserView.as_view(),
        name="active_user",
    ),
    path("profile/", ProfileData.as_view(), name="profile"),
]

src/groups/models.py
from random import randint

from django.db import models
from django.utils.translation import gettext_lazy as _
from faker import Faker

from groups.utils.validators import start_date_validator, student_count_validator
from main.utils.validators import subject_validator


class Group(models.Model):
    name = models.CharField(max_length=200, null=True)
    number = models.PositiveSmallIntegerField()
    students_count = models.PositiveSmallIntegerField(validators=[student_count_validator])
    start_date = models.DateField(null=True, validators=[start_date_validator])
    subject = models.CharField(max_length=100, blank=True, null=True, validators=[subject_validator])
    description = models.TextField(null=True)

    class Meta:
        verbose_name = _("Group")
        verbose_name_plural = _("All groups")

    def __str__(self):
        return f"{self.name} ({self.id})"

    @classmethod
    def generate_instances(cls, count):
        faker = Faker()
        for i in range(count):
            cls.objects.create(
                name=faker.company(),
                number=randint(1, 300),
                students_count=randint(10, 30),
                start_date=faker.date_this_century(),
                subject=faker.word(
                    ext_word_list=[
                        "Math",
                        "Chemistry",
                        "Music",
                        "Physics",
                        "History",
                        "IT",
                    ]
                ),
                description=faker.sentence(nb_words=10),
            )

src/groups/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm

from groups.models import Group


class GroupForm(ModelForm):
    class Meta:
        model = Group
        fields = (
            "name",
            "number",
            "students_count",
            "start_date",
            "subject",
            "description",
        )

    def clean_students_count(self):
        students_count = self.cleaned_data["students_count"]
        if students_count > 30:
            raise ValidationError("The number of students in a group cannot be more than 30")
        return students_count

src/groups/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from groups.forms import GroupForm
from groups.models import Group


class GroupListView(LoginRequiredMixin, ListView):
    model = Group
    template_name = "groups/list.html"
    context_object_name = "groups"

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset


class CreateGroupView(LoginRequiredMixin, CreateView):
    template_name = "groups/create.html"
    form_class = GroupForm
    initial = {"start_date": "2007-10-25"}
    success_url = reverse_lazy("groups:get_groups")


class UpdateGroupView(UpdateView):
    template_name = "groups/update.html"
    form_class = GroupForm
    pk_url_kwarg = "pk"
    queryset = Group.objects.all()
    success_url = reverse_lazy("groups:get_groups")


class DeleteGroupView(DeleteView):
    template_name = "groups/delete.html"
    form_class = GroupForm
    pk_url_kwarg = "pk"
    queryset = Group.objects.all()
    success_url = reverse_lazy("groups:get_groups")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = GroupForm(instance=self.object)
        return context

src/templates/groups/create.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <form method="POST" style="width: 25em; margin: auto">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success" value="Create">Create group</button>
    </form>
{% endblock content %}

src/templates/groups/delete.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <form method="POST" style="width: 25em; margin: auto">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success" value="Delete">Delete group</button>
    </form>
{% endblock content %}

src/templates/groups/list.html
{% extends "index.html" %}

{% block content %}
    <table class="table table-dark table-striped">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Number</th>
            <th scope="col">Students count</th>
            <th scope="col">Start date</th>
            <th scope="col">Subject</th>
            <th scope="col">Description</th>
            <th scope="col">Edit</th>
            <th scope="col">Delete</th>
        </tr>
        </thead>
        <tbody>
        {% for group in groups %}
            <tr>
                <th scope="row">{{ group.pk }}</th>
                <td>{{ group.name }}</td>
                <td>{{ group.number }}</td>
                <td>{{ group.students_count }}</td>
                <td>{{ group.start_date|default:"Unknown" }}</td>
                <td>{{ group.subject }}</td>
                <td>{{ group.description|default:"Unknown" }}</td>
                <th>
                    <a type="button" class="btn btn-warning"
                       href="{% url 'groups:update_group' group.pk %}"
                    >Edit</a>
                </th>
                <th>
                    <a type="button" class="btn btn-danger"
                       href="{% url 'groups:delete_group' group.pk %}"
                    >Delete</a>
                </th>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock content %}

src/templates/groups/update.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <form method="POST" style="width: 25em; margin: auto">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success" value="Update">Update group</button>
    </form>
{% endblock content %}